### ISSUE TITLE
Updated PyPI release?

### ISSUE THREAD

**Issue by CBroz1** [catalystneuro/ndx-miniscope#1]
The current README instructions suggest calling functions that aren't available in the latest version available via pip install (0.2.2).

```python
from ndx-miniscope.miniscope import get_starting_frames
```

Are there plans to update the release? If not, I'll plan to add the repo to the requirements on my end (i.e., git+https:// ...)

**Comment by CodyCBakerPhD** [comment]
Yep, planning to cut this soon to correspond to V3/V4 read/write capabilities on [NeuroConv](https://neuroconv.readthedocs.io/en/main/)

Sorry for the delay!
